apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
        - name: argo
          image: pawankalyan29/healthcare-project:v5
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: argo
spec:
  selector:
    app: argo
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 80  # Port in the NGINX container
  type: NodePort      # Exposes the service externally on the Node's IP and port
